### ISSUE TITLE
Followers/Following is generated from using firebase's Database (Story point: 1)

### ISSUE THREAD

**Issue by Eltom777** [Eltom777/SOEN341-PicturePoint#37] opened 2020-02-13 20:05 UTC
Missing element to finish #24

**Comment by Eltom777** [comment] 2020-02-13 20:08
I created this issue just in case you are not able to connect the profile page to firestorm. We'll be able to close #24 and merge it master, even if that part is missing.

**Comment by a-iacampo** [comment] 2020-02-14 02:38
Successfully connected the user profile card information to firebase #31. Need to connect followers and following to the firebase database.

**Comment by a-iacampo** [comment] 2020-02-28 17:43
Commit f91e796 includes the addition of get follower/followings function

**Comment by a-iacampo** [comment] 2020-02-28 17:45
I don't understand how we are implementing the followers and followings. Needs clarification in the next meeting.

**Comment by Eltom777** [comment] 2020-03-06 15:38
@digathomas has not yet completed the tasks #45. Will push to sprint 4

**Comment by a-iacampo** [comment] 2020-03-22 16:42
Duplicate of #72

**Closed as completed by a-iacampo** 2020-03-22 16:42 UTC
Labels: duplicate, task
